apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet-yearclock
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/OWNER/yearclock-api
    newTag: dev-latest  # CI updates this tag on every push to main
